image: Visual Studio 2017

platform:
  - x64

environment:
  nodejs_version: 10
  FORCE_COLOR: 1

cache:
  - '%LOCALAPPDATA%/Yarn'
  - node_modules -> yarn.lock

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

test_script:
  - yarn test

build: off
